### ISSUE TITLE
puppet failed to install sysbench

### ISSUE THREAD

**Issue by lefred** [jayjanssen/percona-xtradb-cluster-tutorial#23]
notice: /Stage[main]/Percona::Cluster::Packages/Package[Percona-XtraDB-Cluster-client.x86_64]/ensure: created
err: /Stage[main]/Misc/Package[sysbench]/ensure: change from absent to present failed: Execution of '/bin/rpm -i --oldpackage /vagrant/modules/misc/files/sysbench-0.5-3.el6_.x86_64.rpm' returned 1: error: Failed dependencies:
    libaio.so.1()(64bit) is needed by sysbench-0.5-3.el6.x86_64
    libaio.so.1(LIBAIO_0.1)(64bit) is needed by sysbench-0.5-3.el6.x86_64
    libaio.so.1(LIBAIO_0.4)(64bit) is needed by sysbench-0.5-3.el6.x86_64

it's needed or to install libaio before it (it uses rpm -i and not yum) or install it after we have installed all percona packages has they also need libaio (maybe the easiest way to fix it)

**Comment by jayjanssen** [comment]
See if https://github.com/jayjanssen/percona-xtradb-cluster-tutorial/tree/issue_23 fixes the issue for you.

**Comment by jayjanssen** [comment]
https://github.com/jayjanssen/percona-xtradb-cluster-tutorial/commit/67858731092854ddddd6edd21df3c400372e3870
