### ISSUE TITLE
myq_gadgets can be installed by rpm too ;)

### ISSUE THREAD

**Issue by lefred** [jayjanssen/percona-xtradb-cluster-tutorial#24]
instead of using 

notice: /Stage[main]/Misc/Exec[mkdir /root/bin 2> /dev/null; wget -O myq_gadgets-latest.tgz https://github.com/jayjanssen/myq_gadgets/tarball/master && tar xvzf myq_gadgets-latest.tgz -C /root/bin --strip-components=1]/returns: executed successfull

you can install myq_gadgets by rpm too which will uniform all software installation.

**Comment by jayjanssen** [comment]
I change myq_gadgets enough that I dont' want to be tied to a specific version (or now).
