### ISSUE TITLE
Failure on vagrant up command

### ISSUE THREAD

**Issue by joegrasse** [jayjanssen/percona-xtradb-cluster-tutorial#36]
When running 'vagrant up' I get the following error.

Vagrant failed to initialize at a very early stage:

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: D:/GitHub/percona-xtradb-cluster-tutorial/Vagrantfile
Message: uninitialized constant Vagrantfile

OS: Windows 7
VirtualBox: 4.2.12
Vagrant: 1.2.2

**Comment by jayjanssen** [comment]
Hi,
  Can you try with this repo instead: https://github.com/percona/xtradb-cluster-tutorial ?  That's the new home that I'm keeping up to date.

  Also, this seems like a problem with Vagrant.

**Comment by jayjanssen** [comment]
Oh, BTW.  There are two ,Vagrantfiles.<someextension> in the repo and the main Vagrantfile checks out as a symbolic link, at least on Linux.  Maybe that link isn't working right in Windows.  Try copying one of the Vagrantfiles to just 'Vagrantfile' and see if that fixes it.

**Comment by joegrasse** [comment]
I think you hit the nail on the head. When I checkout the project, the Vagrantfile only contains "Vagrantfile.master_slave".
