### ISSUE TITLE
vm.box_url fails with 404 error

### ISSUE THREAD

**Issue by brock-wilson** [jayjanssen/percona-xtradb-cluster-tutorial#37]
Using Windows 7 with Cygwin
Vbox 4.3.20

The URL for vm.box gets a 404, it also fails if entered manually in a browser

 vagrant up
Bringing machine 'node1' up with 'virtualbox' provider...
Bringing machine 'node2' up with 'virtualbox' provider...
Bringing machine 'node3' up with 'virtualbox' provider...
==> node1: Box 'centos6.4-i386-minimal' could not be found. Attempting to find a
nd install...
    node1: Box Provider: virtualbox
    node1: Box Version: >= 0
==> node1: Adding box 'centos6.4-i386-minimal' (v0) for provider: virtualbox
    node1: Downloading: https://dl.dropbox.com/u/2519414/centos6.4-i386-minimal.
box
    node1: Progress: 0% (Rate: 0/s, Estimated time remaining: --:--:--):--)
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found

**Comment by jayjanssen** [comment]
Note:  this repo is no longer maintained.  Use the one here: https://github.com/percona/xtradb-cluster-tutorial
