### ISSUE TITLE
Module: Using Garbd

### ISSUE THREAD

**Issue by jayjanssen** [jayjanssen/percona-xtradb-cluster-tutorial#5]
Taking one node offline and making it garbd instead.

Possibly a requirement for doing "slave from cluster" and "slave to cluster" modules so we have one node that doesn't need run mysqld in the cluster.

**Comment by lefred** [comment]
what is nice is to demonstrate such scenario:
A -> PXC node
B -> PXC node
C -> PXC garbd

Stop (with iptables) communication between A and B and see how C handles that ;)

**Comment by jayjanssen** [comment]
Indeed -- I have a similar scenario already here https://github.com/jayjanssen/percona-xtradb-cluster-tutorial/blob/master/doc/05-Node%20Failure.rst#id4

Those same steps could be used in the garbd module

**Comment by jayjanssen** [comment]
https://github.com/jayjanssen/percona-xtradb-cluster-tutorial/pull/22
